const STORAGE_KEY = "ehon-shelf-books-v1";
const statusLabels = { unread: "まだ読んでいない", reading: "いま読んでいる", read: "読みおわった" };
const ageLabels = { "0-2": "0–2歳", "3-5": "3–5歳", "6+": "6歳以上" };
const coverColors = ["#d98d67", "#719588", "#7897aa", "#a0838b", "#b09a70", "#7f91a3"];
const sampleBooks = [
{id:"sample-1",title:"ぐりとぐら",author:"なかがわ りえこ / おおむら ゆりこ",age:"3-5",status:"read",themes:["どうぶつ","お料理"],note:"大きなカステラの場面がお気に入り。",favorite:true,color:"#d98d67",createdAt:"2026-06-01T09:00:00.000Z"},
{id:"sample-2",title:"しろくまちゃんのほっとけーき",author:"わかやま けん",age:"0-2",status:"reading",themes:["食べもの","生活"],note:"",favorite:true,color:"#719588",createdAt:"2026-06-02T09:00:00.000Z"},
{id:"sample-3",title:"はらぺこあおむし",author:"エリック・カール",age:"0-2",status:"read",themes:["むし","成長"],note:"",favorite:false,color:"#7897aa",createdAt:"2026-06-03T09:00:00.000Z"},
{id:"sample-4",title:"スイミー",author:"レオ・レオニ",age:"6+",status:"unread",themes:["海","勇気"],note:"",favorite:false,color:"#a0838b",createdAt:"2026-06-04T09:00:00.000Z"},
{id:"sample-5",title:"おおきなかぶ",author:"A・トルストイ",age:"3-5",status:"read",themes:["昔話","協力"],note:"",favorite:false,color:"#b09a70",createdAt:"2026-06-05T09:00:00.000Z"},
{id:"sample-6",title:"からすのパンやさん",author:"かこ さとし",age:"3-5",status:"unread",themes:["家族","食べもの"],note:"",favorite:true,color:"#7f91a3",createdAt:"2026-06-06T09:00:00.000Z"}
];
let books=loadBooks(),currentFilter={type:"shelf",value:"all"},currentView="grid",editingBookId=null,toastTimer,installPrompt=null;
const elements={bookGrid:document.querySelector("#bookGrid"),emptyState:document.querySelector("#emptyState"),searchInput:document.querySelector("#searchInput"),sortSelect:document.querySelector("#sortSelect"),sectionKicker:document.querySelector("#sectionKicker"),resultCount:document.querySelector("#resultCount"),activeFilter:document.querySelector("#activeFilter"),activeFilterText:document.querySelector("#activeFilterText"),bookDialog:document.querySelector("#bookDialog"),bookForm:document.querySelector("#bookForm"),dialogTitle:document.querySelector("#dialogTitle"),deleteBookButton:document.querySelector("#deleteBookButton"),toast:document.querySelector("#toast"),sidebar:document.querySelector("#sidebar")};
function loadBooks(){try{const saved=localStorage.getItem(STORAGE_KEY);return saved?JSON.parse(saved):sampleBooks}catch{return sampleBooks}}
function saveBooks(){localStorage.setItem(STORAGE_KEY,JSON.stringify(books))}
function escapeHtml(value=""){return value.replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function getFilteredBooks(){const query=elements.searchInput.value.trim().toLowerCase();let filtered=books.filter(book=>{if(currentFilter.type==="shelf"&&currentFilter.value==="favorite"&&!book.favorite)return false;if(currentFilter.type==="status"&&book.status!==currentFilter.value)return false;if(currentFilter.type==="age"&&book.age!==currentFilter.value)return false;if(!query)return true;return[book.title,book.author,book.note,...book.themes].join(" ").toLowerCase().includes(query)});const sort=elements.sortSelect.value;if(sort==="title")filtered.sort((a,b)=>a.title.localeCompare(b.title,"ja"));else if(sort==="rating")filtered.sort((a,b)=>Number(b.favorite)-Number(a.favorite));else filtered.sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));return filtered}
function render(){const filtered=getFilteredBooks();elements.bookGrid.classList.toggle("list-view",currentView==="list");elements.bookGrid.innerHTML=filtered.map(bookCardTemplate).join("");elements.bookGrid.hidden=filtered.length===0;elements.emptyState.hidden=filtered.length!==0;elements.resultCount.textContent=filtered.length;updateSummary();updateFilterDisplay()}
function bookCardTemplate(book){const themes=book.themes.slice(0,3).map(theme=>`<span class="tag"># ${escapeHtml(theme)}</span>`).join("");return `<article class="book-card" data-id="${book.id}"><div class="cover" style="--cover-color: ${book.color}"><button class="card-menu" type="button" data-action="edit" aria-label="${escapeHtml(book.title)}を編集">•••</button><button class="favorite-button ${book.favorite?"active":""}" type="button" data-action="favorite" aria-label="お気に入り">${book.favorite?"♥":"♡"}</button><div class="cover-book"><span>${escapeHtml(book.title)}</span></div></div><div class="book-card-body"><div class="card-status"><span class="status-dot status-${book.status}"></span>${statusLabels[book.status]}</div><h3 title="${escapeHtml(book.title)}">${escapeHtml(book.title)}</h3><p class="book-author">${escapeHtml(book.author||"作者未登録")}</p><div class="tag-row"><span class="tag">${ageLabels[book.age]}</span>${themes}</div></div></article>`}
function updateSummary(){const readCount=books.filter(book=>book.status==="read").length,unreadCount=books.filter(book=>book.status==="unread").length,favoriteCount=books.filter(book=>book.favorite).length,progress=books.length?Math.round(readCount/books.length*100):0;document.querySelector("#allCount").textContent=books.length;document.querySelector("#favoriteCount").textContent=favoriteCount;document.querySelector("#summaryTotal").textContent=books.length;document.querySelector("#summaryRead").textContent=readCount;document.querySelector("#summaryUnread").textContent=unreadCount;document.querySelector("#summaryProgress").textContent=progress;document.querySelector("#progressBar").style.width=`${progress}%`;document.querySelectorAll("[data-count-status]").forEach(node=>node.textContent=books.filter(book=>book.status===node.dataset.countStatus).length)}
function updateFilterDisplay(){const labels={"shelf:all":"すべての絵本","shelf:favorite":"お気に入り","status:unread":"まだ読んでいない絵本","status:reading":"いま読んでいる絵本","status:read":"読みおわった絵本","age:0-2":"0–2歳向け","age:3-5":"3–5歳向け","age:6+":"6歳以上向け"},key=`${currentFilter.type}:${currentFilter.value}`,isDefault=key==="shelf:all";elements.sectionKicker.textContent=labels[key];elements.activeFilter.hidden=isDefault;elements.activeFilterText.textContent=`${labels[key]}で仕分け中`;document.querySelectorAll(".nav-item").forEach(button=>button.classList.toggle("active",button.dataset.filterType===currentFilter.type&&button.dataset.filterValue===currentFilter.value))}
function openBookDialog(book=null){editingBookId=book?.id??null;elements.dialogTitle.textContent=book?"絵本を編集":"絵本を登録";elements.deleteBookButton.hidden=!book;document.querySelector("#bookId").value=book?.id??"";document.querySelector("#bookTitle").value=book?.title??"";document.querySelector("#bookAuthor").value=book?.author??"";document.querySelector("#bookAge").value=book?.age??"3-5";document.querySelector("#bookStatus").value=book?.status??"unread";document.querySelector("#bookThemes").value=book?.themes.join(", ")??"";document.querySelector("#bookNote").value=book?.note??"";document.querySelector("#bookFavorite").checked=book?.favorite??false;elements.bookDialog.showModal();setTimeout(()=>document.querySelector("#bookTitle").focus(),50)}
function closeBookDialog(){elements.bookDialog.close();elements.bookForm.reset();editingBookId=null}
function handleFormSubmit(event){event.preventDefault();const existing=books.find(book=>book.id===editingBookId),title=document.querySelector("#bookTitle").value.trim();if(!title)return;const book={id:existing?.id??crypto.randomUUID(),title,author:document.querySelector("#bookAuthor").value.trim(),age:document.querySelector("#bookAge").value,status:document.querySelector("#bookStatus").value,themes:document.querySelector("#bookThemes").value.split(/[,、]/).map(theme=>theme.trim()).filter(Boolean),note:document.querySelector("#bookNote").value.trim(),favorite:document.querySelector("#bookFavorite").checked,color:existing?.color??coverColors[books.length%coverColors.length],createdAt:existing?.createdAt??new Date().toISOString()};if(existing){books=books.map(item=>item.id===existing.id?book:item);showToast("絵本の情報を更新しました")}else{books=[book,...books];showToast("新しい絵本を登録しました")}saveBooks();closeBookDialog();render()}
function toggleFavorite(id){books=books.map(book=>book.id===id?{...book,favorite:!book.favorite}:book);saveBooks();render()}
function deleteCurrentBook(){const book=books.find(item=>item.id===editingBookId);if(!book||!confirm(`「${book.title}」を本棚から削除しますか？`))return;books=books.filter(item=>item.id!==editingBookId);saveBooks();closeBookDialog();render();showToast("絵本を削除しました")}
function showToast(message){clearTimeout(toastTimer);elements.toast.textContent=message;elements.toast.classList.add("show");toastTimer=setTimeout(()=>elements.toast.classList.remove("show"),2200)}
function openInstallGuide(){if(installPrompt){installPrompt.prompt();return}const steps=document.querySelector("#installDialog ol"),note=document.querySelector("#installDialog > p");if(location.protocol==="file:"){steps.innerHTML="<li>このフォルダの「README.md」を開きます。</li><li>「Dockに追加する」の手順でローカル起動します。</li><li>Safariの「ファイル」から「Dockに追加」を選びます。</li>";note.textContent="このままでも絵本の登録や仕分けは使えます。Dockへの追加時だけローカル起動が必要です。"}document.querySelector("#installDialog").showModal()}
document.querySelectorAll(".nav-item").forEach(button=>button.addEventListener("click",()=>{currentFilter={type:button.dataset.filterType,value:button.dataset.filterValue};elements.sidebar.classList.remove("open");render()}));
elements.bookGrid.addEventListener("click",event=>{const actionButton=event.target.closest("[data-action]");if(!actionButton)return;const card=actionButton.closest(".book-card");actionButton.dataset.action==="favorite"?toggleFavorite(card.dataset.id):openBookDialog(books.find(book=>book.id===card.dataset.id))});
elements.searchInput.addEventListener("input",render);elements.sortSelect.addEventListener("change",render);elements.bookForm.addEventListener("submit",handleFormSubmit);elements.deleteBookButton.addEventListener("click",deleteCurrentBook);document.querySelector("#addBookButton").addEventListener("click",()=>openBookDialog());document.querySelector("#emptyAddButton").addEventListener("click",()=>openBookDialog());document.querySelector("#dialogClose").addEventListener("click",closeBookDialog);document.querySelector("#cancelButton").addEventListener("click",closeBookDialog);document.querySelector("#clearFilterButton").addEventListener("click",()=>{currentFilter={type:"shelf",value:"all"};render()});document.querySelector("#mobileMenu").addEventListener("click",()=>elements.sidebar.classList.toggle("open"));document.querySelector("#installAppButton").addEventListener("click",openInstallGuide);document.querySelector("#installDialogClose").addEventListener("click",()=>document.querySelector("#installDialog").close());document.querySelector("#installDialogDone").addEventListener("click",()=>document.querySelector("#installDialog").close());
document.querySelector("#gridViewButton").addEventListener("click",event=>{currentView="grid";document.querySelectorAll(".view-toggle button").forEach(button=>button.classList.remove("active"));event.currentTarget.classList.add("active");render()});document.querySelector("#listViewButton").addEventListener("click",event=>{currentView="list";document.querySelectorAll(".view-toggle button").forEach(button=>button.classList.remove("active"));event.currentTarget.classList.add("active");render()});
document.addEventListener("keydown",event=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==="k"){event.preventDefault();elements.searchInput.focus()}if(event.key==="Escape")elements.sidebar.classList.remove("open")});elements.bookDialog.addEventListener("click",event=>{if(event.target===elements.bookDialog)closeBookDialog()});window.addEventListener("beforeinstallprompt",event=>{event.preventDefault();installPrompt=event;document.querySelector("#installAppButton").textContent="Macに追加する"});window.addEventListener("appinstalled",()=>{installPrompt=null;showToast("えほん棚をMacに追加しました")});if("serviceWorker" in navigator&&location.protocol.startsWith("http"))window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js"));render();
